# Generated by Django 5.0.3 on 2024-10-22 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectline',
            name='save_as',
            field=models.TextField(blank=True, null=True),
        ),
    ]
